artifact_uri: file:///media/seagate/Projets_IA/BIHAR2026_TPT_DJALEGA/model/registry/436075709632722480/1c8d77aea5bd4cbe8362a5ea0f137fdd/artifacts
end_time: 1774829096413
entry_point_name: ''
experiment_id: '436075709632722480'
lifecycle_stage: active
run_id: 1c8d77aea5bd4cbe8362a5ea0f137fdd
run_name: LightGBM_V1
source_name: ''
source_type: 4
source_version: ''
start_time: 1774829069505
status: 3
tags: []
user_id: realivanelie
