creation_timestamp: 1775673054392
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1775673054392
model_id: m-b588281c5fab499499438457fb267f64
name: Meteo_LightGBM
run_id: 293cbf88022a4bfc9e0a2fdef5feedd4
run_link: null
source: models:/m-b588281c5fab499499438457fb267f64
status: READY
status_message: null
storage_location: file:///media/seagate/Projets_IA/BIHAR2026_TPT_DJALEGA/model/registry/436075709632722480/models/m-b588281c5fab499499438457fb267f64/artifacts
user_id: null
version: 8
workspace: default
